""" """

import os

os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-21-openjdk-amd64"
import time
import json
from cores.normalizer import TextNormalizer


TEST_TEXTS = [
    # "1. Những ngân hàng đang có lãi suất cho vay bình quân cao như Liên Việt, Bản Việt, Kiên Long với lãi suất từ 8,07 vnđ -  8,94VND...",
    # "2. Từ lâu công viên 30/4 đã trở thành nơi lý tưởng để giới trẻ, du khách chụp ảnh, nhâm nhi ly cà phê hay ngồi dưới tán cây trò chuyện tránh những ngày nắng nóng. Công viên 23-9 nằm giữa hai con đường Lê Lai và Phạm Ngũ Lão, trải dài từ công trường Quách Thị Trang đến đường Nguyễn Trãi. Công viên gồm 3 khu và bị ngăn cách nhau bởi đường Nguyễn Thị Nghĩa.",
    # "3. Bộ Quốc phòng Nga đồng thời tuyên bố hệ thống phòng không Nga đã bắn hạ 46 máy bay không người lái của Ukraine, một tên lửa ATACMS và 8 quả bom thông minh Hammer trong 24 giờ qua.",
    # "4. Lấy cảm hứng từ chiếc xe quan tài Dracula xuất hiện trong tập phim năm 1965 của series phim truyền hình The Munsters",
    # "5. Lãnh đạo Sở GD-ĐT TP.HCM cho biết về nguyên tắc xét điểm chuẩn lớp 10 trường, lớp chuyên như sau: Chỉ xét tuyển đối với thí sinh tham dự đủ các bài thi quy định, không vi phạm nội quy trong kỳ thi tuyển sinh và các bài thi đều đạt điểm lớn hơn 2.",
    # "Trở thành Software Engineer (SE) với mức lương Upto $3,500 tại VietDevelopers!",
    # "hôm nay là 23/03/2025.",
    # "Tôi có 5 con mèo. 100 người tham gia. Trận đấu diễn ra lúc 14:30. Cuộc họp bắt đầu lúc 9:05.",
    # "TP.HCM, ngày 30/04/2025 14:30. Tôi đổi 100 USD sang VNĐ. Giá xăng hôm nay: 22.500 VNĐ/lít. TP.HCM là thành phố lớn.",
    # "5kg gạo. Tôi đổi 100 USD sang VNĐ.",
    # "Theo WHO, số ca mắc COVID-19 đang có xu hướng giảm.",
    # "Giá xăng tăng lên 25.000đ/lít.",
    # "Sân bay mới có diện tích 120ha 1.000,50€ 50 - 100%.",
    # "Phải nói thật nhé, thương mại điện tử giờ vừa tiện vừa... ức chế kinh khủng! Vui có, bực có, hào hứng có, mà đôi khi muốn \"xả stress\" cũng chỉ cần lướt app mua sắm vài vòng là đủ drama cho cả ngày.\nCó ai như mình không, vừa định săn sale iPhone 14 Pro Max 128GB, tưởng đâu sẽ là chiến lợi phẩm, thế mà trong vòng chưa đầy 1 giây — hết hàng! Cảm giác lúc đó như muốn \"bốc hoả\"! Thế nhưng chẳng lâu sau, mở qua thấy AirPods Pro (Giá: 5.200.000 VNĐ), Apple Watch Series 8 (Giá: 9.000.000 VNĐ), Smart TV LG 4K (Giá: 12.500.000 VNĐ), Robot hút bụi Xiaomi (Giá: 3.200.000 VNĐ) giảm giá sập sàn — cảm giác như trúng số vậy! Cảm xúc cứ như chơi tàu lượn siêu tốc, lên rồi xuống, chẳng thể nào bình tĩnh nổi.\nThế mà khi mua đồ gia dụng như Máy lạnh Daikin (Giá: 14.000.000 VNĐ), Panasonic (Giá: 10.500.000 VNĐ), LG (Giá: 11.000.000 VNĐ), Midea (Giá: 8.500.000 VNĐ), mình cứ nghĩ sẽ yên tâm với những món đồ xịn sò. Nhưng đọc review xong, chỉ muốn... khóc thét. Máy lạnh mát đấy nhưng mà ship về thì nguyên cái thùng móp méo như thể bị... đi phượt về. Trời ơi, ai mà không tức! Nhưng rồi, tìm được cái shop uy tín, giao hàng nhanh, bảo hành đầy đủ — tự dưng lại yêu thương mại điện tử như yêu người yêu cũ quay lại làm hòa vậy.\nMua đồ công nghệ thôi chưa đủ, giờ người ta còn tìm việc, tìm nhà, tìm phòng... online luôn. Mình đã thử apply CV qua các nền tảng như Viettel (Website: viettel.com.vn), DevUP (Email: hr@devup.com), và Freelancer — nhưng mà chờ hoài không thấy tin nhắn từ HR rep. Cảm giác lúc đó thì chỉ muốn hét lên: \"Ơ kìa, có đọc CV không mà cứ seen không trả lời!\" Nhưng mà, khi nhận được offer lương cao, job Remote, và Benefits/Commission hấp dẫn thì... ôi dào, bực mình lúc trước chợt biến mất.\nRiêng mảng bất động sản online cũng đầy cảm xúc dở khóc dở cười. Tìm thấy Vinhomes (Website: vinhomes.vn), Times City, Masteri, Sky Villa nghe sang chảnh vậy đó, nhưng khi bấm vô xem giá thì... muốn ngã ngửa: \"Ôi trời, làm sao mà mua được?\" Thế là đành quay lại tìm chung cư mini, giá hợp lý hơn, full nội thất, wifi mạnh, gần Vinmart, WC sạch sẽ — vậy cũng đủ vui rồi.\nCông nhận, thương mại điện tử chính là thế giới không ngủ. Một bên là người mua sẵn sàng \"chốt đơn thần tốc\", một bên là người bán canh deal, tối ưu ads, chạy KPI mệt mỏi. Các thương hiệu thì cứ liên tục đua nhau tung ra sản phẩm mới, với đủ loại Marketing, Livestream, Digital đến mức người dùng chỉ biết thốt lên: \"Trời ơi, ví em không chịu nổi nữa đâu!\" Và đó... là cái hay, cái điên, cái vui, cái tức... mà chỉ có ai mê thương mại điện tử mới hiểu được hết!",
    # "Hôm nay là 23 tháng 3 năm 2025, nhiệt độ ngoài trời là 27°C, nhưng vào buổi tối sẽ giảm xuống chỉ còn 18°C. Tôi vừa mua một chiếc iPhone 14 Pro Max tại Apple Store với giá 30 triệu đồng. Màn hình của nó có kích thước 6.7 inch (tương đương 17 cm) và độ dày khoảng 7.65 mm nặng 30gr, 2kg, 3km2. Điện thoại này chạy trên hệ điều hành iOS 16, rất mượt mà và tối ưu.",
    # "Tối nay, tôi sẽ gọi cho đối tác tại số 0912345678 để thảo luận về Dự án AI. Sau đó, tôi sẽ tiếp tục theo dõi chương trình flashsale livestream trên Tiktok, nơi đang giảm giá 30% cho các sản phẩm công nghệ.",
    # "Tỷ lệ thất nghiệp giảm còn 3.5%.",
    # "Sở hữu Sky Villa không chỉ là tận hưởng không gian sống đẳng cấp, mà còn là trải nghiệm toàn diện với sân golf riêng, sân tennis tiêu chuẩn, spa thư giãn mỗi tối, phòng gym hiện đại mở cửa 24/7, bể bơi vô cực, vườn thiền trên cao ngay trong khuôn viên. Tất cả chỉ cách trung tâm Hà Nội 15 phút lái xe, với mức giá từ 18 tỷ, hỗ trợ vay lên đến 70% và miễn phí quản lý trong 2 năm đầu",
    # "Trải nghiệm không gian sống luxury giữa lòng Hà Nội với căn hộ VIP tại Times City, nơi hội tụ đầy đủ tiện ích: trung tâm thương mại, trường học quốc tế, bể bơi 4 mùa, sân vườn xanh mát, cùng hệ thống an ninh 24/7. Giá ưu đãi từ 4.8 tỷ, hỗ trợ trả góp linh hoạt trong 25 năm.",
    # "Chương trình khuyến mãi hot nhất tháng đang diễn ra đồng thời trên Facebook, Instagram và TikTok, với hàng trăm mã giảm giá tới 50%, freeship toàn quốc, cùng video review chân thực từ KOLs. Đừng quên tham gia mini game để rinh quà trị giá đến 5 triệu đồng!",
    # "Honda SH 125i bản tiêu chuẩn giá khoảng 86 triệu, trong khi bản 160i phanh ABS lên tới hơn 100 triệu. Không biết có đáng để bỏ thêm tiền để lấy bản 160i không?",
    # "Cần bán MacBook Pro 2022 và điện thoại! Mình đang cần thanh lý MacBook Pro 2022, máy sử dụng tốt, cấu hình cao, thích hợp cho công việc đồ họa và lập trình. Ngoài ra, mình cũng có 2 chiếc điện thoại Samsung Galaxy S21 và iPhone 13 Pro Max muốn bán lại. Cả hai đều còn mới, không trầy xước, và vẫn còn bảo hành chính hãng. Ngoài ra, mình cũng có chiếc Oppo Reno 7 muốn bán với giá cực ưu đãi. Nếu ai đang cần mua Sim 4G hoặc 5G giá tốt thì liên hệ mình luôn nhé, mình có mấy loại sim của các nhà mạng lớn sẵn sàng giao ngay. Ai có nhu cầu, vui lòng liên hệ để thương lượng giá cả hợp lý.",
    "Thương mại điện tử bây giờ đúng là vừa yêu vừa ghét, vừa cười vừa tức, đúng kiểu \"trò chơi cảm xúc\" của dân sống online. Có những ngày, mở app Shopee, Lazada, Tiki, nhìn deal iPhone 14 Pro Max 128GB (Giá: 29.990.000 VNĐ), MacBook Pro M2 13-inch (Giá: 35.000.000 VNĐ), Smart TV LG 4K (Giá: 12.500.000 VNĐ), Robot hút bụi Xiaomi (Giá: 3.200.000 VNĐ) giảm giá tới 50% mà vui sướng như bắt được vàng. Giỏ hàng thì đầy ắp đồ — nào là sữa Meiji (Giá: 500.000 VNĐ), bỉm Bobby (Giá: 220.000 VNĐ), camera chống trộm (Giá: 1.500.000 VNĐ), máy lạnh Daikin (Giá: 14.000.000 VNĐ), bình sữa Pigeon (Giá: 250.000 VNĐ) — nhấn thanh toán mà tim đập loạn xạ như lần đầu tỏ tình crush rep tin nhắn. Cảm giác ấy không gì thay thế được!\nNhưng mà đời không như mơ đâu nha! Đặt hàng online cũng đầy drama không kém phim Hàn. Có lần đi thuê chung cư mini full nội thất (Giá thuê: 5.000.000 VNĐ/tháng), quảng cáo thì view sông, view hồ, view thành phố triệu đô... đến nơi thì WC bé tí, wifi lag, sofa ọp ẹp như hàng donate. Có hôm săn được vé limousine VIP (Giá: 500.000 VNĐ), tưởng được đi sang chảnh, ai dè xe dừng đón khách dọc đường như xe buýt, tức không chịu nổi! Chưa kể có lần đặt máy chiếu 4K (Giá: 8.000.000 VNĐ), đợi shipper mòn mỏi, cuối cùng bị boom hàng. Thật sự lúc đó chỉ muốn livestream chửi nguyên team sale, QC, marketing luôn cho bõ tức.\nNhưng cay đắng vậy mà rồi cũng lại mềm lòng. Vì thương mại điện tử giờ len lỏi vào từng ngóc ngách cuộc sống rồi. Mình thích cái cảm giác được làm \"người tiêu dùng thông minh\" — tối tối nằm trong căn hộ Vinhomes Central Park (Địa chỉ: 208 Nguyễn Hữu Cảnh, Bình Thạnh, TP.HCM), bật Smart Home, chỉnh đèn đổi màu bằng giọng nói, điều khiển điều hoà qua app, mở nhạc chill trên Bluetooth. Sáng thì không cần ra siêu thị chen chúc, chỉ cần vài cú click là có Omega-3 (Giá: 350.000 VNĐ), Vitamin D3 (Giá: 150.000 VNĐ), Collagen (Giá: 400.000 VNĐ) ship tận giường. Cuối tuần order thêm cái sofa mới (Giá: 7.000.000 VNĐ), tậu thêm robot lau nhà Xiaomi (Giá: 3.200.000 VNĐ), đặt thêm túi bỉm Pampers (Giá: 230.000 VNĐ) cho bé — cuộc sống vừa tiện nghi, vừa chill, vừa công nghệ.\nThương mại điện tử đúng là vậy đó — có vui, có bực, có lầy, có chill, có cả drama lẫn hạnh phúc. Và mình — một đứa nghiện shopping online — biết chắc chắn rằng, dù có \"bóc phốt\" cỡ nào thì ngày mai... vẫn tiếp tục quẹt app order tiếp như chưa từng tức giận!"
]


if __name__ == "__main__":
    tik = time.time()
    text_normalizer = TextNormalizer("./.cached/exps/vncorenlp/")
    print(f"[*] take {time.time() - tik} seconds to load model")
    tik = time.time()
    for text_inputs in TEST_TEXTS:
        text_outputs = text_normalizer(text_inputs)
        print (text_outputs)
    print(f"[*] take {time.time() - tik} seconds to normalize {len(TEST_TEXTS)} texts")
